# 
# for Biodiversity app demo

vars:
  hosts:
    concombre:
      fixture_filename: andes_v3_ac702790_2024_02_06_19_03_21_mysql.sql
      web_port: 12340
      db_port: 12341
      git_sha: ac702790
      host: concombre

local:
  hosts:
    concombre:

preprod:
  hosts:
    concombre:

andes_monolithic:
  hosts:
    concombre: