---
main:
  vars:
    ansible_connection: lxd
    ansible_user: root
    ansible_become: no

    # Variables for microservice deployment
    andes_dir: /opt/andes
    db_user_name: andes_user
    #db_user_password: ENTER_ANDES_PASSWORD_HERE # connection access restricted from andes-web host (django account)
    db_user_password: smellyfish123* # connection access restricted from andes-web host (django account)
    db_ro_password: ENTER_RO_PASSWORD_HERE # no connection restrictions, but read-only (debugging account)
    #db_root_password: ENTER_ROOT_PASSWORD_HERE # can only log-in locally (from andes-db host)
    db_root_password: smellyfish123* # can only log-in locally (from andes-db host)
    db_name: andesdb
    db_port: 3306
    db_host: andes-db.lxd
    web_host: andes-web.lxd



all:
  children:
    main:
      hosts:
        andes-web:
          ansible_connection: local
        andes-db:
          ansible_connection: local
        nginx-proxy:
          ansible_connection: local
          
    postprod:
      hosts:
        cabot2023:
          ansible_connection: lxd
          ansible_user: root
          ansible_become: no
          ansible_lxd_remote: local

    local:
      hosts:
        andes-web:
          ansible_connection: lxd
          ansible_user: root
          ansible_become: no
          ansible_lxd_remote: local
        andes-db:
          ansible_connection: lxd
          ansible_user: root
          ansible_become: no
          ansible_lxd_remote: local
        nginx-proxy:
          ansible_connection: lxd
          ansible_user: root
          ansible_become: no
          ansible_lxd_remote: local
      hosts:
        cabot2023:
          ansible_connection: lxd
          ansible_user: root
          ansible_become: no
          ansible_lxd_remote: local


