# The Andes stack needs two containers andes-web webserver and andes-db database server
# Web request must be forwarded to the andes-web container.
# The andes-web container must access andes-db
# An additional nginx-proxy container will forward web requests to andes-web
# Optional database (read-only) connections to the database can be made via the proxy.
# The andes-web container will need a github deploy key to download the code.
# Supply the private part of the key as ./files/id_rsa_andes
# and it will be copied to the container
# to update the code/fixtures, use the update_fixtures.yaml playbook
---

- name: Andes webserver Install apt software dependencies
  hosts: andes-web
  tasks:

    - name: Install apt requirements
      apt:
        update_cache: yes
        pkg: 
          - git
          - apache2
          - libapache2-mod-wsgi-py3
          - python3
          - python3-pip
          - gettext 
          - libapache2-mod-wsgi-py3
          - redis
          - default-libmysqlclient-dev
          # these are needed for printer
          - cups
          - libcups2-dev 
          # these are required for building Pillow
          - python3-dev
          - python3-setuptools
          - libjpeg8-dev 
        state: present
 
  ### START setup CELERY

    - name: Ensure celery group exists
      ansible.builtin.group:
        name: celery
        state: present

    - name: Add the celery user
      ansible.builtin.user:
        name: celery
        comment: user for managing celery daemon
        create_home: false
        password: '!' # disabled password
        groups: celery, www-data

    - name: Create the celery conf
      ansible.builtin.template:
        src: ../templates/celeryd_conf.j2
        dest: /etc/default/celeryd
        owner: root
        group: root

    - name: Create the run directory
      ansible.builtin.file:
          path: /var/run/celery
          state: directory
          mode: 0771 # go rwx
          group: www-data

    - name: Create the celery log directory
      ansible.builtin.file:
          path: /var/log/celery
          state: directory
          mode: 0771 # go rwx
          group: www-data

    - name: Enable and start red-s-server
      ansible.builtin.systemd:
        name:  redis-server.service
        state: started
        enabled: true

    - name: write celery systemd service from jinja2 template
      ansible.builtin.template:
        src: ../templates/celeryd_service.j2
        dest: /etc/systemd/system/celeryd.service
        owner: root
        group: root

    - name: write celery beat systemd service from jinja2 template
      ansible.builtin.template:
        src: ../templates/celerybeat_service.j2
        dest: /etc/systemd/system/celerybeat.service
        owner: root
        group: root

    - name: Enable and start celeryd.service
      ansible.builtin.systemd:
        name:  celeryd.service
        state: started
        enabled: true

    - name: Enable and start celerybeat.service
      ansible.builtin.systemd:
        name:  celerybeat.service
        state: started
        enabled: true
    ### END setup CELERY

    - name: Git init, make ssh dir
      file:
        path: /root/.ssh/
        state: directory

    - name: Git init, Copy private key
      copy:
        src: ../files/id_rsa_andes
        dest: /root/.ssh/id_rsa_andes
        owner: root
        group: root
        mode: 0600

    - name: Git init, Copy config file
      copy: 
        src: ../files/ssh_config
        dest: /root/.ssh/config
        owner: root
        group: root
        mode: 0644

    - name: Git init, clone the repo
      git:
        repo: git@github.com:dfo-gulf-science/andes.git
        force: true
        accept_hostkey: true
        key_file: /root/.ssh/id_rsa_andes
        dest: "{{ andes_dir }}/"
         
    - name: pip install requirements
      ansible.builtin.pip:
        requirements: "{{ andes_dir }}/requirements.txt"

    - name: pip install special requirements
      ansible.builtin.pip:
        requirements: "{{ andes_dir }}/special_requirements.txt"

    - name: write .env from jinja2 template
      ansible.builtin.template:
        src: ../templates/andes_env.j2
        dest: "/{{ andes_dir }}/.env"
        owner: root
        group: root

    - name: Create the tmp directory
      ansible.builtin.file:
          path: "/{{ andes_dir }}/media/temp"
          state: directory
          mode: '0770' # go rwx
          group: www-data
          owner: www-data   
    #
    # Need to add this to settings/py
    #CSRF_TRUSTED_ORIGINS = ['http://iml-science-1.ent.dfo-mpo.ca']
    #

    - name: Django Check
      command: /usr/bin/python3 {{ andes_dir }}/manage.py check

    - name: Django Migrate
      command: /usr/bin/python3 {{ andes_dir }}/manage.py migrate

    - name: Django compilemessages
      command: /usr/bin/python3 {{ andes_dir }}/manage.py compilemessages

    - name: Django collectstatic
      command: /usr/bin/python3 {{ andes_dir }}/manage.py collectstatic --no-input
      # notify: Reload Apache

    - name: Set up Apache 
      copy:
        src: ../files/apache_conf
        dest: /etc/apache2/sites-available/000-default.conf
        owner: root
        group: root
      # notify: Reload Apache

    - name: Reload Apache 
      service:
        name: apache2
        state: reloaded

  # handlers:
  #   - name: Reload Apache
  #     service:
  #       name: apache2
  #       state: reloaded

