# The Andes stack needs two containers andes-web webserver and andes-db database server
# Web request must be forwarded to the andes-web container.
# The andes-web container must access andes-db
# An additional nginx-proxy container will forward web requests to andes-web
# Optional database (read-only) connections to the database can be made via the proxy.
# The andes-web container will need a github deploy key to download the code.
# Supply the private part of the key as ./files/id_rsa_andes
# and it will be copied to the container
# to update the code/fixtures, use the update_fixtures.yaml playbook

# installs a reverse proxy to handle web requests to the host.
# As of now, it simply forwards requests to the andes-web container
# More exotic configurations are planned, as this host will serve more than one webapp
# To work, lxc must forward all web requests to this container.
# i.e., use the proxy-web lxc profile.
---

- name: Proxy Install apt software dependencies
  hosts: nginx-proxy
  tasks:
    - name: Install nginx
      apt:
        update_cache: yes
        pkg: 
          - nginx
          - ssl-cert
        state: present

    - name: Disable nginx default
      file:
        path: /etc/nginx/sites-enabled/default
        state: absent

    - name: write gninx site conf from jinja2 template
      ansible.builtin.template:
        src: ../templates/nginx_conf.j2
        dest: /etc/nginx/nginx.conf
        owner: root
        group: root

    # - name: create log files

    - name: Restart nginx
      service:
        name: nginx
        state: restarted
        enabled: true

