# Update the andes code from git.
# will perform migrations, make messages and build the web static files
---

- name: Update Andes
  hosts: andes-web
  tasks:

    - name: Git init, clone the repo
      git:
        repo: git@github.com:dfo-gulf-science/andes.git
        force: true
        accept_hostkey: true
        key_file: /root/.ssh/id_rsa_andes
        dest: "{{ andes_dir }}/"
        version: stage
          
    - name: pip install requirements
      ansible.builtin.pip:
        requirements: "{{ andes_dir }}/requirements.txt"

    - name: pip install special requirements
      ansible.builtin.pip:
        requirements: "{{ andes_dir }}/special_requirements.txt"

    - name: add tweak in settings.py
      ansible.builtin.lineinfile:
        path: "{{ andes_dir}}/andes/settings.py"
        line: SECURE_CROSS_ORIGIN_OPENER_POLICY = None
    
    - name: add another tweak in settings.py
      ansible.builtin.lineinfile:
        path: "{{ andes_dir}}/andes/settings.py"
        line: CSRF_TRUSTED_ORIGINS = ['http://iml-science-1.ent.dfo-mpo.ca']

    - name: Django Check
      command: /usr/bin/python3 {{ andes_dir }}/manage.py check

    - name: Django Migrate
      command: /usr/bin/python3 {{ andes_dir }}/manage.py migrate

    - name: Django compilemessages
      command: /usr/bin/python3 {{ andes_dir }}/manage.py compilemessages

    - name: Django collectstatic
      command: /usr/bin/python3 {{ andes_dir }}/manage.py collectstatic --no-input

    - name: Reload Apache 
      service:
        name: apache2
        state: reloaded


